### ISSUE TITLE
setup.cfg and install_requires

### ISSUE THREAD

**Issue by eight04** [jnoortheen/pipm#1]
Package dependencies are often put in the `install_requires` field of `setup.cfg` like:
https://github.com/eight04/ptt-article-parser/blob/de6639fbd0797e7c2fe9df853ed82cbeeed49bb4/setup.cfg#L30-L32

Is it possible to sync the version number with `install_requires` after `pipm install/uninstall`? For example:
```
# requirements.txt
a==0.1.0
b==0.2.0

# setup.cfg
a~=0.1.0
b~=0.2.0
```
After running command `pipm update a`
```
# requirements.txt
a==0.2.1
b==0.2.0

# setup.cfg
a~=0.2.1
b~=0.2.0
```

**Comment by jnoortheen** [comment]
It is possible to implement such feature. Currently `pipm` relies on the `pip`'s ability to manipulate requirements files. If you are interested in adding this feature, Have a look at [update command](https://github.com/jnoortheen/pipm/blob/36d08189a74c10d4d924c8fdf9a341860c202daf/pipm/commands.py#L168). [This](https://docs.python.org/2/library/configparser.html) can be used as the config parser.

**Comment by eight04** [comment]
I made a tool which uses `setup.cfg` to save production dependency:
https://pypi.org/project/vpip/

It is built on top of py3's venv, so it doesn't work with py2.
