### ISSUE TITLE
requirements-dev.txt instead of dev-requirements.txt

### ISSUE THREAD

**Issue by paulvi** [jnoortheen/pipm#13]
Using filename suffixes instead of prefixes, 
requirements-dev.txt instead of dev-requirements.txt,
will make all requirements-*.txt close together in project root.

I understand that is more complicated when doing in compatible with older project.

**Comment by jnoortheen** [comment]
that pattern is already supported. https://github.com/jnoortheen/pipm/blob/47caa6e29fd3ad529846930d9cd184c0e518aa35/pipm/file_utils.py#L37

**Comment by paulvi** [comment]
oh, ok

What are default names now for dev/test ?

**Comment by jnoortheen** [comment]
that would be `requirements-dev.txt` & `requirements-test.txt`. It should pickup if those file exist already.

**Comment by paulvi** [comment]
Great!

**Comment by paulvi** [comment]
Maybe you should rename files in this repository to show recommended / default example

**Comment by jnoortheen** [comment]
A PR is always welcome! 
![image](https://user-images.githubusercontent.com/6702219/121347362-bb2a4200-c944-11eb-8e72-17884995456e.png)
